CREATE TABLE IF NOT EXISTS Aeroport (
    IdIata TEXT NOT NULL PRIMARY KEY,
    Nom TEXT NOT NULL,
    Ville TEXT NOT NULL,
    Pays TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Avion (
    IdAvion INTEGER PRIMARY KEY AUTOINCREMENT,
    Model TEXT NOT NULL,
    Capacite INTEGER NOT NULL,
    Statut TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Personnel (
    IdPersonnel INTEGER PRIMARY KEY AUTOINCREMENT,
    Nom TEXT NOT NULL,
    Prenom TEXT NOT NULL,
    Role TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Passager (
    IdPassager INTEGER PRIMARY KEY AUTOINCREMENT,
    Nom TEXT NOT NULL,
    Prenom TEXT NOT NULL,
    Nationalite TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Vol (
    IdVol INTEGER PRIMARY KEY AUTOINCREMENT,
    NumeroVol TEXT NOT NULL,
    DateDepart TEXT NOT NULL,
    DateArrivee TEXT NOT NULL,
    Statut TEXT NOT NULL,
    AeroportDepart TEXT NOT NULL,
    AeroportArrivee TEXT NOT NULL,
    IdAvion INTEGER NOT NULL,
    IdCommandant INTEGER NOT NULL,
    FOREIGN KEY (AeroportDepart) REFERENCES Aeroport(IdIata) ON DELETE RESTRICT,
    FOREIGN KEY (AeroportArrivee) REFERENCES Aeroport(IdIata) ON DELETE RESTRICT,
    FOREIGN KEY (IdAvion) REFERENCES Avion(IdAvion) ON DELETE RESTRICT,
    FOREIGN KEY (IdCommandant) REFERENCES Personnel(IdPersonnel) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS Reservation (
    IdReservation INTEGER PRIMARY KEY AUTOINCREMENT,
    Numerosiege TEXT NOT NULL,
    IdVol INTEGER NOT NULL,
    IdPassager INTEGER NOT NULL,
    FOREIGN KEY (IdVol) REFERENCES Vol(IdVol) ON DELETE CASCADE,
    FOREIGN KEY (IdPassager) REFERENCES Passager(IdPassager) ON DELETE CASCADE,
    UNIQUE (IdVol, Numerosiege)
);